// Downloads the IBM Plex faces the site uses and writes public/styles/fonts.css.
//
// This is a maintenance tool, not a build step. Its output is committed, so a
// Cloudflare Pages build never depends on Google being reachable. Re-run it by
// hand only to add a weight or pick up a new font version.
//
// Why self-host at all: every page type here loaded a render-blocking
// stylesheet from fonts.googleapis.com, which costs a DNS lookup, a TLS
// handshake and a round trip before any text can paint, and then points at a
// second origin for the files. Cache partitioning killed the shared-cache
// argument for Google Fonts back in 2020, so there is nothing left on the
// other side of that trade.
//
// Sans ships a variable version covering wght 100-700 in both upright and
// italic, which replaces five static weights plus two italics. Mono has no
// variable version on Google Fonts, so it stays static at the three weights
// the site actually asks for.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const FONT_DIR = path.join(root, 'public/fonts')
const CSS_OUT = path.join(root, 'public/styles/fonts.css')

// Google serves woff2 only to browsers it recognises.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

const FAMILIES = [
  {
    slug: 'ibm-plex-sans',
    family: 'IBM Plex Sans',
    url: 'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100..700;1,100..700&display=swap',
  },
  {
    slug: 'ibm-plex-mono',
    family: 'IBM Plex Mono',
    url: 'https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@300;400;500&display=swap',
  },
]

// Anything beyond these two is dead weight for an English-language site. The
// unicode-range on each rule means latin-ext is only fetched by a page that
// actually contains one of its characters.
const SUBSETS = new Set(['latin', 'latin-ext'])

function parse(css) {
  const out = []
  const re = /\/\* (\S+) \*\/\s*@font-face \{([\s\S]*?)\}/g
  let m
  while ((m = re.exec(css))) {
    const [, subset, body] = m
    if (!SUBSETS.has(subset)) continue
    const get = (k) => body.match(new RegExp(`${k}: ([^;]+);`))?.[1]
    out.push({
      subset,
      style: get('font-style'),
      weight: get('font-weight'),
      range: get('unicode-range'),
      url: body.match(/url\((\S+?)\)/)[1],
    })
  }
  return out
}

async function main() {
  fs.mkdirSync(FONT_DIR, { recursive: true })
  fs.mkdirSync(path.dirname(CSS_OUT), { recursive: true })

  const rules = []
  let bytes = 0

  for (const fam of FAMILIES) {
    const res = await fetch(fam.url, { headers: { 'User-Agent': UA } })
    if (!res.ok) throw new Error(`${fam.family}: CSS request returned ${res.status}`)
    const faces = parse(await res.text())
    if (!faces.length) throw new Error(`${fam.family}: no latin faces found`)

    for (const f of faces) {
      // "100 700" is a variable range; a bare number is a static weight.
      const tag = f.weight.includes(' ') ? 'var' : f.weight
      const name = `${fam.slug}-${f.style}-${tag}-${f.subset}.woff2`
      const dest = path.join(FONT_DIR, name)

      const file = await fetch(f.url, { headers: { 'User-Agent': UA } })
      if (!file.ok) throw new Error(`${name}: download returned ${file.status}`)
      const buf = Buffer.from(await file.arrayBuffer())
      fs.writeFileSync(dest, buf)
      bytes += buf.length

      rules.push(
        `/* ${fam.family} ${f.style} ${f.weight} ${f.subset} */\n` +
          `@font-face {\n` +
          `  font-family: '${fam.family}';\n` +
          `  font-style: ${f.style};\n` +
          `  font-weight: ${f.weight};\n` +
          `  font-display: swap;\n` +
          `  src: url('/fonts/${name}') format('woff2');\n` +
          `  unicode-range: ${f.range};\n` +
          `}`
      )
      console.log(`  ${name.padEnd(44)} ${(buf.length / 1024).toFixed(1)} KB`)
    }
  }

  const header =
    `/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand. */\n` +
    `/* Re-run: node scripts/fetch-fonts.mjs */\n\n`
  fs.writeFileSync(CSS_OUT, header + rules.join('\n\n') + '\n')

  console.log(`\n${rules.length} faces, ${(bytes / 1024).toFixed(0)} KB total`)
  console.log(`Wrote ${path.relative(root, CSS_OUT)}`)
}

main().catch((e) => {
  console.error('Fonts:', e.message)
  process.exit(1)
})
